### ISSUE TITLE
multipleSRC problem

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [joeherold/wp_uuid_create#1]
Hey Joe,
thank you for this extension. saved me a lot time :)
I found a bug in the convertMultiField function.
In this function the variable $backup will not be setted, so it's always empty und the loop always continueing.

**Comment by joeherold** [comment]
Hi Monique,

danke fürs fixen!
Dachte nicht dass dieses Modul noch jemand verwendet... :) 

LG, Johannes
